 
export class Rates {
constructor(
	minHTER_er:Number,
  minHTER_tr: Number,
  minHTER_frr: Number,
  minHTER_ver: Number,
  minHTER_far: Number,
  EER_er: Number,
  EER_tr: Number,
  EER_frr: Number,
  EER_ver: Number,
  EER_far: Number,
  FRR_01FAR_er: Number,
  FRR_01FAR_tr: Number,
  FRR_01FAR_frr: Number,
  FRR_01FAR_ver: Number,
  FRR_01FAR_far: Number,
  FRR_10FAR_er: Number,
  FRR_10FAR_tr: Number,
  FRR_10FAR_frr: Number,
  FRR_10FAR_ver: Number,
  FRR_10FAR_far: Number,
  VER_001FAR_er: Number,
  VER_001FAR_tr: Number,
  VER_001FAR_frr: Number,
  VER_001FAR_ver: Number,
  VER_001FAR_far: Number,
  VER_01FAR_er: Number,
  VER_01FAR_tr: Number,
  VER_01FAR_frr: Number,
  VER_01FAR_ver:Number,
  VER_01FAR_far: Number,
  VER_1FAR_er: Number,
  VER_1FAR_tr: Number,
  VER_1FAR_frr: Number,
  VER_1FAR_ver: Number,
  VER_1FAR_far: Number ){}
 }